In [7]:
import tensorflow as tf
import numpy as np

In [6]:
const = tf.constant(34)
const

<tf.Tensor: shape=(), dtype=int32, numpy=34>

In [17]:
constant = tf.constant(np.array([[2,3,4,9],[5,6,7,8]]).astype('int32'))

In [18]:
constant

<tf.Tensor: shape=(2, 4), dtype=int32, numpy=
array([[2, 3, 4, 9],
       [5, 6, 7, 8]], dtype=int32)>