In [12]:
import tensorflow as tf
import numpy as np  
## In TensorFlow, the difference between tf.ones() and tf.ones_like() is the same idea as in NumPy or PyTorch — but applied to tensors.

In [13]:
ones = tf.ones((2,2),dtype=tf.int32,name = "Zzz")
ones

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 1],
       [1, 1]], dtype=int32)>

In [14]:
def one_intializer(shape , dtype, intializer) :
    return tf.Variable(intializer(shape=shape , dtype = dtype))

In [15]:
ones = one_intializer((2,2),tf.int32, tf.ones_initializer())
ones

<tf.Variable 'Variable:0' shape=(2, 2) dtype=int32, numpy=
array([[1, 1],
       [1, 1]], dtype=int32)>

In [16]:
import tensorflow as tf

initializer = tf.keras.initializers.Ones()

# Example: Dense layer with Ones initializer
layer = tf.keras.layers.Dense(
    units=3,
    kernel_initializer=initializer,
    bias_initializer=initializer
)

# Dummy input
x = tf.constant([[1.0, 2.0]])
y = layer(x)

print("Weights:\n", layer.kernel.numpy())
print("Bias:\n", layer.bias.numpy())

Weights:
 [[1. 1. 1.]
 [1. 1. 1.]]
Bias:
 [1. 1. 1.]
