In [1]:
import tensorflow as tf 
import numpy as np

2026-02-21 21:00:51.225202: I external/local_xla/xla/tsl/cuda/cudart_stub.cc:31] Could not find cuda drivers on your machine, GPU will not be used.
2026-02-21 21:00:51.506100: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2026-02-21 21:00:52.969854: I external/local_xla/xla/tsl/cuda/cudart_stub.cc:31] Could not find cuda drivers on your machine, GPU will not be used.


In [11]:
tf_todense = tf.sparse.SparseTensor(indices =[[0,0],[1,1],[2,2],[3,3]] ,values =[1,2,3,4] ,dense_shape=(4,4))   ## indices = [row,column] in which value are stored , values = which value are stored in the matrix , dense_shape = shape of matrix 1D,2D,3D

In [12]:
tf_todense

SparseTensor(indices=tf.Tensor(
[[0 0]
 [1 1]
 [2 2]
 [3 3]], shape=(4, 2), dtype=int64), values=tf.Tensor([1 2 3 4], shape=(4,), dtype=int32), dense_shape=tf.Tensor([4 4], shape=(2,), dtype=int64))

In [13]:
tf_tosparse  = tf.sparse.to_dense(tf_todense)

In [14]:
tf_tosparse

<tf.Tensor: shape=(4, 4), dtype=int32, numpy=
array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]], dtype=int32)>

In [15]:
tf.SparseTensor(indices =[[0,0],[1,1],[2,2],[3,3]] ,values =[1,2,3,4] ,dense_shape=(4,4)) 

SparseTensor(indices=tf.Tensor(
[[0 0]
 [1 1]
 [2 2]
 [3 3]], shape=(4, 2), dtype=int64), values=tf.Tensor([1 2 3 4], shape=(4,), dtype=int32), dense_shape=tf.Tensor([4 4], shape=(2,), dtype=int64))