In [1]:
import tensorflow as tf
import numpy as np

2026-02-20 20:59:42.772723: I external/local_xla/xla/tsl/cuda/cudart_stub.cc:31] Could not find cuda drivers on your machine, GPU will not be used.
2026-02-20 20:59:43.242176: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2026-02-20 20:59:45.872003: I external/local_xla/xla/tsl/cuda/cudart_stub.cc:31] Could not find cuda drivers on your machine, GPU will not be used.


In [23]:
var = tf.Variable(2)
var1 = tf.Variable(2)


In [24]:
print(var+var1)

tf.Tensor(4, shape=(), dtype=int32)


In [25]:
mul = tf.Variable(np.array([[2,3,4],[5,6,7]]))
mul1 = tf.Variable(np.array([[5,6,7],[2,3,4]]))


print(mul*mul1)

tf.Tensor(
[[10 18 28]
 [10 18 28]], shape=(2, 3), dtype=int64)


In [26]:
mul

<tf.Variable 'Variable:0' shape=(2, 3) dtype=int64, numpy=
array([[2, 3, 4],
       [5, 6, 7]])>

In [27]:
new_mul = mul.assign([[2,9,9],[5,6,7]])

In [28]:
print(new_mul*mul)

tf.Tensor(
[[ 4 81 81]
 [25 36 49]], shape=(2, 3), dtype=int64)


In [29]:
new_add = new_mul.assign_add([[2,3,4],[5,6,7]])
print(new_add)

<tf.Variable 'UnreadVariable' shape=(2, 3) dtype=int64, numpy=
array([[ 4, 12, 13],
       [10, 12, 14]])>


In [31]:
var1.name

'Variable:0'