In [18]:
import tensorflow as tf
import numpy as np

In [19]:
var = tf.Variable(2)
var1 = tf.Variable(2)


In [20]:
print(var+var1)

tf.Tensor(4, shape=(), dtype=int32)


In [26]:
mul = tf.Variable(np.array([[2,3,4],[5,6,7]]))
mul1 = tf.Variable(np.array([[5,6,7],[2,3,4]]))


print(mul*mul1)

tf.Tensor(
[[10 18 28]
 [10 18 28]], shape=(2, 3), dtype=int64)


In [27]:
mul

<tf.Variable 'Variable:0' shape=(2, 3) dtype=int64, numpy=
array([[2, 3, 4],
       [5, 6, 7]])>

In [ ]:
from tensorflow.keras.models import Sequential