In [1]:
import tensorflow as tf
import numpy as np

2026-02-22 13:51:06.392009: I external/local_xla/xla/tsl/cuda/cudart_stub.cc:31] Could not find cuda drivers on your machine, GPU will not be used.
2026-02-22 13:51:06.849264: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2026-02-22 13:51:09.509542: I external/local_xla/xla/tsl/cuda/cudart_stub.cc:31] Could not find cuda drivers on your machine, GPU will not be used.


In [3]:
ones = tf.ones([2,2],dtype = tf.int32)
ones

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 1],
       [1, 1]], dtype=int32)>

In [5]:
ones_ = tf.ones([2,2,4],dtype = tf.int32)  # it direct creates ones
ones_

<tf.Tensor: shape=(2, 2, 4), dtype=int32, numpy=
array([[[1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int32)>

# Ones_ like

In [9]:
ones_like_1D = tf.ones_like(ones_,dtype = tf.int32)

print(ones_like_1D)  # one_like take input to create ones matrix

tf.Tensor(
[[[1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]]], shape=(2, 2, 4), dtype=int32)


# Ones_Intializer

In [18]:
def ones_intializer(shape , dtype , intializer) :
    return tf.Variable(intializer(shape=shape,dtype=dtype))

In [19]:
print(ones_intializer((2,2), tf.int32 , tf.ones_initializer()))

<tf.Variable 'Variable:0' shape=(2, 2) dtype=int32, numpy=
array([[1, 1],
       [1, 1]], dtype=int32)>
