In [1]:
import numpy as np

In [2]:
# 1. Create a NumPy array of numbers from 1 to 10.

arr_ = np.array(range(1,11))
print(arr_)

[ 1  2  3  4  5  6  7  8  9 10]


In [3]:
# 2. Create a 3×3 matrix filled with zeros.
arr1 = np.zeros((3,3))
print(arr1)


[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [4]:
 # 3. Create a 3×3 identity matrix.
arr_1 = np.eye((3))
print(arr_1)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [5]:
# 4. Create an array of 10 evenly spaced numbeer between 5 and 50
arr_1 = np.linspace(5,50, 10).astype('int64')
print(arr_1)

[ 5 10 15 20 25 30 35 40 45 50]


In [6]:
# 5. Find the shape ,size and datatype of a Numpy array
shape= np.shape(arr_1)
size= np.size(arr_1)
print(arr1.dtype)

print(shape)
print(size)
#data_type

float64
(10,)
10


In [7]:
 # 6. From an array [10,20,30,40,50,60], extract ,
 #        * only even-indexed elements
 #        * elements greater than 30

arr = np.array([10,20,30,40,50,60])

even = arr[arr % 2 ==0]
print(even)
greater = arr[arr> 30]
print(greater)

[10 20 30 40 50 60]
[40 50 60]


In [8]:
# Given a 2D array (4×4), extract:
#         * first row
#         * last column
#         * middle 2×2 matrix
import random
arr = np.random.randint(1,100, size=(4,4))
print(arr)
print(arr[0]) 
print(arr[:,3])

[[56 83  2 12]
 [ 8 73 64 42]
 [ 7 78  4 97]
 [82 76  8 88]]
[56 83  2 12]
[12 42 97 88]


In [9]:
# 8. Replace all values greater than 25 with 0.
arr = np.array([[10,25,30],[40,25,60]])

new_arr = np.where(arr > 25 , 0,arr)   # np.where(condition,yesthan,nothan)
print(new_arr)


[[10 25  0]
 [ 0 25  0]]


In [10]:
# 9. Add 5 to every element of an array without using loops.
arr = np.random.randint(1,10,size=(1,4))
new_arr = np.sum(arr)
print(arr)
print("Sum :",new_arr)

[[4 8 7 7]]
Sum : 26


In [11]:
# 10.Multiply two arrays element-wise.
arr1 = np.random.randint(1,5,size = (1,4))
arr2 = np.random.randint(1,5,size = (1,4))
new_arr = arr1*arr2
print(arr1)
print(arr2)
print(new_arr)


[[3 3 4 4]]
[[1 3 4 2]]
[[ 3  9 16  8]]


In [12]:
# 11. Square every element of a NumPy array.
arr = np.random.randint(1,10,size=(1,5))
new_arr = arr**2
print(arr)
print(new_arr)


[[2 3 6 7 8]]
[[ 4  9 36 49 64]]


In [13]:
# 12. Find the sum, mean, max, min, and standard deviation of an array.
arr = np.random.randint(1,10,size=(1,5))
sum_ = np.sum(arr)
mean_ = np.mean(arr)
max_ = np.max(arr)
min_ = np.min(arr)
standard_deviation = np.std(arr)

print(arr)
print(sum_)
print(mean_)
print(max_)
print(min_)
print(standard_deviation)


[[1 4 3 2 7]]
17
3.4
7
1
2.0591260281974


In [14]:
# 13. Normalize an array (values between 0 and 1).
arr = np.random.randint(1,10,size=(1,5))

normalized = (arr - arr.min())  / (arr.max() - arr.min())

print(arr)
print(normalized)


[[6 8 5 9 2]]
[[0.57142857 0.85714286 0.42857143 1.         0.        ]]


In [15]:
# 14. Converts a 1D array of size 12 into 3 x 4 matrix
import numpy as np
arr = np.array([20,90,67,87,45,16,33,89,76,90,45,65])
new_arr = np.reshape(arr,shape=(3,4))

print(new_arr)

[[20 90 67 87]
 [45 16 33 89]
 [76 90 45 65]]


In [16]:
#15 . flatten a 2D array into 1D
import random
arr = np.random.randint(10,50,size=(3,3))
print(arr) 
new_arr = arr.flatten()
print(new_arr)

[[26 17 33]
 [29 14 47]
 [49 35 38]]
[26 17 33 29 14 47 49 35 38]


In [17]:
#16. stack two arrays 
#     * vertically
#     * horizontally

arr1 = np.array([34,24,20,34,47,89,64])
arr2 = np.array([78,34,23,45,23,14,90])

new_arr1 = np.vstack((arr1,arr2))
new_arr2 = np.hstack((arr1,arr2))
print("Vertically stack :" ,new_arr1)
print("Horizontally stack : ",new_arr2)


Vertically stack : [[34 24 20 34 47 89 64]
 [78 34 23 45 23 14 90]]
Horizontally stack :  [34 24 20 34 47 89 64 78 34 23 45 23 14 90]


In [18]:
# 17. Split an array of size 10 into 5 equal parts
size =10
reshaped = np.linspace(1,10,5)
print(reshaped)

[ 1.    3.25  5.5   7.75 10.  ]


In [19]:
# 18. Generate 100 random integers between 1 and 100

import random
arr = np.random.randint(1,100,size=(4,4))
print(arr)


[[87 29 59 70]
 [36  8 74 30]
 [45  4  3 62]
 [92 28 27 11]]


In [20]:
# 19. Count how many values are greater than 50
row_count = 0
for arr_ in arr:
    if (arr_> 50).any() :
        row_count = row_count+1
print("Element greater than 50 in row",row_count)
column_count = 0
for arr_ in arr.T:
    if (arr_> 50).any() :
        column_count = column_count+1
print("Element gretaer than 50 in column :",column_count)

Element greater than 50 in row 4
Element gretaer than 50 in column : 3


In [21]:
# 20. Replace all odd number with -1 
import random 
import numpy as np
arr = np.random.randint(1,10,size=(2,2))
print(arr)

arr[arr%2!=0] = -1
print(arr)

[[3 8]
 [2 9]]
[[-1  8]
 [ 2 -1]]


In [22]:
# 21. set a random seed and prove the output  is reproduceable
import random  
np.random.seed(42)
arr = np.random.randint(1,10,size = 5)
print(arr)

[7 4 8 5 7]


In [23]:
#22. Given a marks array of 50 students:
# find topper
# find average
# count students above average

np.random.seed(42)
arr = np.random.randint(1,50,size= 50)
print(arr)
topper = np.max(arr)
print("Topper is :",topper)

avg = np.average(arr)
print("Average is :",avg)

above_avg = arr[arr > avg ]
print("Above average :",above_avg)

[39 29 15 43  8 21 39 19 23 11 11 24 36 40 24  3 22  2 24 44 30 38  2 21
 33 12 22 44 25 49 27 42 28 16 15 47 44  3 37  7 21  9 39 18  4 25 14  9
 26  2]
Topper is : 49
Average is : 23.72
Above average : [39 29 43 39 24 36 40 24 24 44 30 38 33 44 25 49 27 42 28 47 44 37 39 25
 26]


In [24]:
#23. create a 5x5 matrix and :
#set border value to 1
#inner value to 0

arr = np.zeros((5,5))
arr

arr[0] = 1
arr[4] = 1
arr[:,0] = 1
arr[:,4] = 1

print(arr)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [25]:
# 24. Find duplicate elements in a NumPy array.
import numpy as np
np.random.seed(42)
arr = np.random.randint(1,50,size=50)
print(arr)
print(np.rec.find_duplicate(arr))

[39 29 15 43  8 21 39 19 23 11 11 24 36 40 24  3 22  2 24 44 30 38  2 21
 33 12 22 44 25 49 27 42 28 16 15 47 44  3 37  7 21  9 39 18  4 25 14  9
 26  2]
[np.int64(39), np.int64(15), np.int64(21), np.int64(11), np.int64(24), np.int64(3), np.int64(22), np.int64(2), np.int64(44), np.int64(25), np.int64(9)]


In [26]:
# 25. Compute row-wise and column-wise sums of a matrix.
np.random.seed(42)
(42)
arr = np.random.randint(1,10,size = (2,2))
print(arr)

row= arr[0] + arr [1]
column = arr[:,0] + arr[:,1]
print("Row sum :",row)
print("column sum :",column)


[[7 4]
 [8 5]]
Row sum : [15  9]
column sum : [11 13]


In [27]:
arr = np.array([1,2,3,4,5] , dtype = np.int32)

arr.astype('int64')

print(arr.nbytes)

20
